language: python
python: "3.6"
install:
    - pip install -r requirements.txt
script:
    - pytest backend/src/dataCollector_Test.py
    - pytest backend/src/dataSeparatorTest.py
    - pytest backend/src/dataAnalyticsTest.py
